IntelliSOFT-Consulting/ssemr

configuration/etl_ddl/hiv_care_enrolment/hiv_enrolment.sql

@moshonk I have pushed the ddl script for the hiv enrolment

DDL script for the hiv care enrolment

---

distro/configuration/addresshierarchy/addressConfiguration.xml
distro/configuration/addresshierarchy/addressTemplate.xml

@moshonk I removed village zone, village chief, direction to care giver and renamed the village to village/town

update the addressTemplate

---

configuration/etl_ddl/adults_and_adolescent_Intake/adult_and_adolescent_intake.sql

@moshonk adding patient_id and encounter_id to the adult and adolescent etl

Ddl adult and adolescent form

---

distro/configuration/ampathforms/adult_adolescent_intake_form.json

@moshonk The laboratory finding questions have not included since I could not find concepts to represent the results. Once this is confirmed then I will add them.

Add Adult and Adolescent intake Form

---

distro/configuration/concepts/hiv_family_history_concepts.csv

adding concepts to the hiv_family_history

adding concepts to the hiv_family_history

---

frontend/spa-build-config.json

@moshonk Adding Reports link to the spa build

Adding Reports link to the spa build

---

distro/configuration/ampathforms/hiv_care_follow_up_form.json

Combining Follow up and Tb screening form

Combining Follow up and Tb screening form

---

distro/configuration/ampathforms/vl_laboratory_request.json

changed phone number from integer to text

changed phone number from integer to text

---

distro/configuration/ampathforms/vl_laboratory_request.json
frontend/spa-build-config.json

Redirect the Reports link to open in a new tab

Redirect the Reports link to open in a new tab

---

distro/configuration/ampathforms/hiv_care_follow_up_form.json
distro/configuration/ampathforms/vl_laboratory_request.json
frontend/spa-build-config.json

SSEMR-49 Hide type of TB when TB treatment is marked as No

SSEMR-49 Hide type of TB when TB treatment is marked as No

---

distro/configuration/ampathforms/end_of_follow_up.json

@moshonk Adding list of facilities as a dropdown

Adding list of facilities

---

distro/configuration/ampathforms/high_viral_load.json

Adding Pill Count and Pill percentage on 2nd and 3rd EAC sessions plus other minor changes

Adding Pill Count and Pill percentage on 2nd and 3rd EAC sessions plus other minor changes

---

distro/configuration/ampathforms/high_viral_load.json
distro/configuration/ampathforms/hiv_enrollment_form.json

Adding the Name of the previous clinic, Place of HIV testing, and Place of HIV retesting as dropdowns

Adding the Name of the previous clinic, Place of HIV testing and Place of HIV retesting as dropdowns

---

distro/configuration/ampathforms/hiv_and_art_care.json

@moshonk Made changes to the HIV ART dropdown

Made the initial ART dropdown list all regimens

---

distro/configuration/ampathforms/high_viral_load.json
distro/configuration/ampathforms/hiv_enrollment_form.json
frontend/config.json

@moshonk Fixing the Unable to fetch person attribute type phone Error

Fixing the Unable to fetch person attribute type phone Error

---

distro/configuration/ampathforms/high_viral_load.json
distro/configuration/ampathforms/hiv_care_follow_up_form.json
distro/configuration/ampathforms/hiv_enrollment_form.json
frontend/config.json

@moshonk SSEMR-58 Adding field for 'Date Viral Load Results Received' after the 'Viral Load Results field
'

SSEMR-58 Adding field for 'Date Viral Load Results Received' after the 'Viral Load Results field '

---

distro/configuration/ampathforms/high_viral_load.json
distro/configuration/ampathforms/hiv_care_follow_up_form.json
distro/configuration/ampathforms/hiv_enrollment_form.json
frontend/config.json

SSEMR-61 Capturing pill count in EAC 1

---

distro/configuration/ampathforms/adult_adolescent_intake_form.json
distro/configuration/ampathforms/art_interruption.json
distro/configuration/ampathforms/community_linkage_logbook.json
distro/configuration/ampathforms/end_of_follow_up.json
distro/configuration/ampathforms/high_viral_load.json
distro/configuration/ampathforms/hiv_care_follow_up_form.json
distro/configuration/ampathforms/hiv_enrollment_form.json
distro/configuration/ampathforms/peads_hiv_care_and_treatment_intake_form.json
distro/configuration/ampathforms/vl_laboratory_request.json

Organizing the forms in a descending order

---

distro/configuration/ampathforms/hiv_care_follow_up_form.json

This PR addresses the issues in this ticket; https://intellisoftkenya.atlassian.net/browse/SSEMR-140

SSEMR-140 Follow up form - Side Effects, New OI and WHO Stage

---

distro/configuration/ampathforms/high_viral_load.json

SSEMR-138 High VL option

---

distro/configuration/ampathforms/adult_adolescent_intake_form.json
distro/configuration/ampathforms/peads_hiv_care_and_treatment_intake_form.json

Set the temperature validations for both the adults and children to be between 32 and 40

SSEMR-298 Introduc e additional temeperature range for sick clients

---

distro/configuration/ampathforms/hiv_care_follow_up_form.json

@Michaelndula @PiusKariuki please review.

SSEMR-302 (Follow Up Form) ARV Pills - Introduce an 'Other' option

---

distro/configuration/ampathforms/art_interruption.json
distro/configuration/ampathforms/follow_up_outcome.json
distro/configuration/ampathforms/high_viral_load.json
distro/configuration/ampathforms/hiv_and_art_care.json
distro/configuration/ampathforms/hiv_care_follow_up_form.json
distro/configuration/ampathforms/hiv_enrollment_form.json
frontend/spa-build-config.json

I have switched to the react form engine and changed all the concepts with the hide expression to 'required: false'. @PiusKariuki @Michaelndula please review

SSEMR-188 Change to react form engine

---

distro/configuration/ampathforms/hiv_and_art_care.json

This PR is related to this issue, https://intellisoftkenya.atlassian.net/browse/SSEMR-328. @Michaelndula @PiusKariuki please review.

SSEMR-328 Add other field and fix phone number regex

---

distro/configuration/ampathforms/hiv_care_follow_up_form.json
frontend/spa-build-config.json

I have tested out the different versions, the one that also fixes the BMI problem we were having. The problem is that it doesn't fix the issue with the auto population for the height and weight.

SSEMR-319 Add Autopopulation to the Forms.

---

frontend/spa-assemble-config.json

@Michaelndula @PiusKariuki please review.

bump patient summary version

---

backupcron.sh

Delete backup file from container after copying to local and sending to remote server.

---

distro/configuration/ampathforms/hiv_and_art_care.json
distro/configuration/concepts/hiv_family_history_concept_set.csv
distro/configuration/concepts/hiv_family_history_concepts.csv
distro/configuration/concepts/hiv_personal_history_concepts.csv

…it Cohort to only take month and year (MM/YYYY)

SSEMR-469 Forms (C. 6 - Personal, Family, and treatment history) - Edit Cohort to only take month and year (MM/YYYY)

---

distro/configuration/attributetypes/attribute_types-core_demo.csv
frontend/config.json

SSEMR-473 Appointments - Display Patient Unique ART Number instead of OpenMRS ID

---

distro/configuration/ampathforms/high_viral_load.json

validate the dates for EAC, i.e EAC1 can’t be future dates as well as a future date than EAC2 & EAC3; the EAC 2 date cant be before the EAC 1 date, and the EAC 3 date can't be before the EAC 1 and EAC 2 dates.

SSEMR-557 High VL Form Validation issues

---

distro/pom.xml
frontend/spa-assemble-config.json

…counters appearing at the top.

SSEMR-617 "all encounters" section should be organized with latest encounters appearing at the top.

---

distro/pom.xml
setup.sh

(fix) Adding the Repsy repository configurations to pull custom modules deployed to repsy.
